title: "Mikaylah Hanson Portfolio"
description: "Undergraduate Student at the University of Minnesota"
theme: minima
baseurl: ""  # Leave empty for GitHub Pages
url: "https://MikaylahHanson.github.io"

# Navigation Links
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/

# Author Info
author:
  name: "Mikaylah Hanson"
  email: "mikaylahhanson9@gmail.com"
  links:
    - https://github.com/MikaylahHanson







