title: Mikaylah Hanson Portfolio
description: Physics and Astrophysics Student
theme: minima
baseurl: ""
url: "https://MikaylahHanson.github.io"

# Navigation Links
nav_links:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about/
  - title: "Projects"
    url: /projects/

