title: "Mikaylah Hanson"
description: "Undergraduate Student at the University of Minnesota"
theme: minimal-mistakes-jekyll
baseurl: ""
url: "https://MikaylahHanson.github.io"

# Sidebar settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

# Navigation links
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/

# Author Profile
author:
  name: "Mikaylah Hanson"
  avatar: "/assets/images/avatar.png"  # Optional image
  bio: "Undergraduate Student at the University of Minnesota"
  location: "Minneapolis, MN"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/MikaylahHanson"






