title: "Mikaylah Hanson"
description: "Undergraduate Student at the University of Minnesota"
theme: "minimal-mistakes-jekyll"
baseurl: ""  # For GitHub Pages, this should be empty
url: "https://MikaylahHanson.github.io"

# Optional: Customize the navigation bar links (sidebar)
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/

# Author Info (Optional, you can display this in the sidebar)
author:
  name: "Mikaylah Hanson"
  email: "mikaylahhanson9@gmail.com"
  avatar: "/assets/images/avatar.png"  # Put your avatar image in the assets folder (optional)

# Sidebar configuration
show_sidebar: true  # Make sure sidebar is shown






